language: node_js
node_js:
  - "8"

jobs:
  include:
    - stage: test and lint
      env:
        - lintAndTest=test
        - lintAndTest=lint
      script: "npm run $lintAndTest"
    - stage: security
      script: npx nsp check
