language: node_js

cache:
  directories:
  - node_modules # NPM packages

  node_js:
  - "8"

jobs:
  include:
    - stage: test and lint
      script:
        - npm run lint
        - npm run test
    - stage: security
      script: npx nsp check
