language: node_js

node_js:
  - "8"

# jobs:
#   include:
#     - stage: test and lint
#       script:
#         - npm run lint
#         - npm run test
#     - stage: security
#       script: npx nsp check

jobs:
  include:
    - stage: test
      script: npx nsp check
    - # stage name not required, will continue to use `test`
      script: npm run test
    - stage: deploy
      script: npm run lint